/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.18
 * Generated at: 2026-02-06 07:50:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.service_005fjsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class RP_005f104118_005fselect_005fsetrealrowsize_005fnexacrojsp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/xml; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String userid = request.getParameter("userid");
    String username = request.getParameter("username");

      out.write("\r\n");
      out.write("<Root xmlns=\"http://www.nexacroplatform.com/platform/dataset\">\r\n");
      out.write("    <Parameters>\r\n");
      out.write("        <Parameter id=\"ErrorCode\" type=\"int\">0</Parameter>\r\n");
      out.write("        <Parameter id=\"ErrorMsg\" type=\"string\">Success (Mock)</Parameter>\r\n");
      out.write("    </Parameters>\r\n");
      out.write("    <Dataset id=\"output\">\r\n");
      out.write("        <ColumnInfo>\r\n");
      out.write("            <Column id=\"IDX\" type=\"string\" size=\"5\"/>\r\n");
      out.write("            <Column id=\"ObjectName\" type=\"string\" size=\"100\"/>\r\n");
      out.write("            <Column id=\"ObjectID\" type=\"string\" size=\"200\"/>\r\n");
      out.write("            <Column id=\"TestType\" type=\"string\" size=\"8\"/>\r\n");
      out.write("            <Column id=\"TestObject\" type=\"string\" size=\"10\"/>\r\n");
      out.write("            <Column id=\"TestValue\" type=\"string\" size=\"100\"/>\r\n");
      out.write("            <Column id=\"ResultValue\" type=\"string\" size=\"10\"/>\r\n");
      out.write("        </ColumnInfo>\r\n");
      out.write("        <Rows>\r\n");
      out.write("            <Row>\r\n");
      out.write("                <Col id=\"IDX\">1</Col>\r\n");
      out.write("                <Col id=\"ObjectName\">TestUser</Col>\r\n");
      out.write("                <Col id=\"ObjectID\">");
      out.print( userid != null ? userid : "unknown" );
      out.write("</Col>\r\n");
      out.write("                <Col id=\"TestType\">A</Col>\r\n");
      out.write("                <Col id=\"TestObject\">Obj1</Col>\r\n");
      out.write("                <Col id=\"TestValue\">");
      out.print( username != null ? username : "test" );
      out.write("</Col>\r\n");
      out.write("                <Col id=\"ResultValue\">OK</Col>\r\n");
      out.write("            </Row>\r\n");
      out.write("        </Rows>\r\n");
      out.write("    </Dataset>\r\n");
      out.write("</Root>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
